name: connect-issue-project
on:
  issues:
    types:
      - assigned

jobs:
  #If a issue is assigned, move issue to 'To do' column
  raise-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: DevKor_DevOps
          column: To do
          repo-token: ${{secrets.connect_issue_project_workflow}}
    